target("test_bicycle_feedforward_controller")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_feedforward_controller.cpp")
    add_deps("bicycle_feedforward_controller")
target_end()

target("test_bicycle_pid_controller")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_pid_controller.cpp")
    add_deps("bicycle_pid_controller")
target_end()

target("test_bicycle_model_predictive_controller")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_model_predictive_controller.cpp")
    add_deps("bicycle_model_predictive_controller")
target_end()

target("test_bicycle_kinematics_flow_controller")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_kinematics_flow_controller.cpp")
    add_deps("bicycle_kinematics_flow_controller")
target_end()
