target("test_math_mdfunction_proxy")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_mdfunction_proxy.cpp")
    add_deps("math_mdfunction_proxy", "math_vector", "math_vectorx", "math_matrix", "math_matrixx", "math_linear_mdfunction", "math_quadratic_mdfunction", "math_rosenbrock_function")
target_end()

target("test_math_linear_mdfunction")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_linear_mdfunction.cpp")
    add_deps("math_vector", "math_vectorx", "math_linear_mdfunction")
target_end()

target("test_math_quadratic_mdfunction")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_quadratic_mdfunction.cpp")
    add_deps("math_vector", "math_vectorx", "math_matrix", "math_matrixx", "math_quadratic_mdfunction")
target_end()

target("test_math_rosenbrock_function")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_rosenbrock_function.cpp")
    add_deps("math_vec2", "math_rosenbrock_function")
target_end()
