target("test_math_function_proxy")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_function_proxy.cpp")
    add_deps("math_function_proxy", "math_piecewise_linear_function", "math_piecewise_cubic_function", "math_piecewise_quintic_function")
target_end()

target("test_math_piecewise_linear_function1")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_linear_function1.cpp")
    add_deps("math_piecewise_linear_function", "math_utils")
target_end()

target("test_math_piecewise_cubic_function1")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_cubic_function1.cpp")
    add_deps("math_piecewise_cubic_function")
target_end()

target("test_math_piecewise_quintic_function1")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_quintic_function1.cpp")
    add_deps("math_piecewise_quintic_function")
target_end()
