target("test_cvxopm_osqp_solver")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_osqp_solver.cpp")
    add_deps("cvxopm_osqp_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info", "cvxopm_osqp_solver")
target_end()

target("test_cvxopm_lnsrch_solver")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_lnsrch_solver.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_lnsrch_solver")
target_end()

target("test_cvxopm_bfgs_solver")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_bfgs_solver.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_bfgs_solver")
target_end()

target("test_cvxopm_lbfgs_solver")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_lbfgs_solver.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_lbfgs_solver")
target_end()

target("test_cvxopm_amoeba_solver")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_amoeba_solver.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_amoeba_solver")
target_end()
