target("test_math_curve_proxy")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_curve_proxy.cpp")
    add_deps("math_curve_proxy", "math_piecewise_linear_curve", "math_piecewise_cubic_curve", "math_piecewise_quintic_curve")
target_end()

target("test_math_piecewise_linear_curve2")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_linear_curve2.cpp")
    add_deps("math_piecewise_linear_curve")
target_end()

target("test_math_piecewise_cubic_curve2")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_cubic_curve2.cpp")
    add_deps("math_piecewise_cubic_curve")
target_end()

target("test_math_piecewise_quintic_curve2")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_quintic_curve2.cpp")
    add_deps("math_piecewise_quintic_curve")
target_end()

target("test_math_piecewise_linear_curve3")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_linear_curve3.cpp")
    add_deps("math_piecewise_linear_curve")
target_end()

target("test_math_piecewise_cubic_curve3")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_cubic_curve3.cpp")
    add_deps("math_piecewise_cubic_curve")
target_end()

target("test_math_piecewise_quintic_curve3")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_piecewise_quintic_curve3.cpp")
    add_deps("math_piecewise_quintic_curve")
target_end()
