target("math_dense_trait")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("dense_trait.hpp")
    add_deps("common_aligned_allocator", "math_concepts")
target_end()

target("math_dense_dot_trait")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("detail/dense_dot_trait.hpp")
    add_deps("math_concepts", "math_dense_trait")
target_end()

target("math_dense_transposed_trait")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("detail/dense_transposed_trait.hpp")
    add_deps("math_concepts", "math_dense_trait")
target_end()

target("math_dense_arithmetic_base")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("dense_arithmetic_base.hpp", "detail/dense_norm_trait.hpp")
    add_deps("math_concepts", "math_dense_trait", "blas_lapack")
target_end()

target("math_vector_base")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("vector_base.hpp")
    add_deps("math_concepts", "math_dense_arithmetic_base", "math_dense_dot_trait", "math_type_traits", "blas_lapack")
target_end()

target("math_vector")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("vector.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_concepts", "math_dense_trait", "math_vector_base", "blas_lapack")
target_end()

target("math_matrix_base")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("matrix_base.hpp")
    add_deps("math_concepts", "math_dense_arithmetic_base", "math_dense_dot_trait", "math_dense_transposed_trait", "math_type_traits", "blas_lapack")
target_end()

target("math_matrix")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("matrix.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_concepts", "math_dense_trait", "math_matrix_base", "blas_lapack")
target_end()

target("math_lu_dcmp")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("lu_dcmp.hpp", "detail/dense_partial_pivot_trait.hpp")
    add_deps("math_concepts", "blas_lapack")
target_end()

target("math_qr_dcmp")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("qr_dcmp.hpp", "detail/dense_degenerate_trait.hpp", "detail/dense_generate_trait.hpp")
    add_deps("math_concepts", "blas_lapack")
target_end()

target("math_vec2")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("vec2.hpp", "detail/dense_norm_trait.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_concepts", "math_dense_trait")
target_end()

target("math_vec3")
    set_kind("headeronly")
    add_includedirs("../../..")
    add_headerfiles("vec3.hpp", "detail/dense_norm_trait.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("common_in_in_in_out_result", "math_concepts", "math_dense_trait")
target_end()
