target("test_bicycle_route_line_cubic_acc_planner")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_route_line_cubic_acc_planner.cpp")
    add_deps("bicycle_route_line_cubic_acc_planner")
target_end()

target("test_bicycle_route_line_quintic_acc_planner")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_route_line_quintic_acc_planner.cpp")
    add_deps("bicycle_route_line_quintic_acc_planner")
target_end()

target("test_bicycle_route_line_cubic_offset_planner")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_route_line_cubic_offset_planner.cpp")
    add_deps("bicycle_route_line_cubic_offset_planner")
target_end()

target("test_bicycle_route_line_quintic_offset_planner")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_route_line_quintic_offset_planner.cpp")
    add_deps("bicycle_route_line_quintic_offset_planner")
target_end()

target("test_bicycle_route_line_kinematics_planner")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_route_line_kinematics_planner.cpp")
    add_deps("bicycle_route_line_kinematics_planner")
target_end()
