target("test_cvxopm_osqp_problem")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_osqp_problem.cpp")
    add_deps("cvxopm_osqp_problem")
target_end()

target("test_cvxopm_dense_problem")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_dense_problem.cpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_utils", "math_vectorx", "math_matrixx", "math_linear_mdfunction", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem")
target_end()
