target("test_math_vector")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_vector.cpp")
    add_deps("math_matrix", "math_vector", "math_dense_arithmetic_base")
target_end()

target("test_math_vec2")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_vec2.cpp")
    add_deps("math_vec2")
target_end()

target("test_math_vec3")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_vec3.cpp")
    add_deps("math_vec3")
target_end()

target("test_math_matrix")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_matrix.cpp")
    add_deps("math_matrix", "math_dense_arithmetic_base")
target_end()

target("test_math_lu_dcmp")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_lu_dcmp.cpp")
    add_deps("math_type_traits", "math_lu_dcmp", "math_vector", "math_vector", "math_matrix", "math_dense_arithmetic_base")
target_end()

target("test_math_qr_dcmp")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_qr_dcmp.cpp")
    add_deps("math_type_traits", "math_qr_dcmp", "math_vector", "math_vector", "math_matrix", "math_dense_arithmetic_base")
target_end()
