target("test_math_sparse_matrix_proxy")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_sparse_matrix_proxy.cpp")
    add_deps("math_sparse_matrix_proxy", "math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csc_matrix", "math_csr_matrix")
target_end()

target("test_math_dok_matrix")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_dok_matrix.cpp")
    add_deps("math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csc_matrix", "math_csr_matrix")
target_end()

target("test_math_lil_matrix")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_lil_matrix.cpp")
    add_deps("math_lil_matrix", "math_dok_matrix", "math_coo_matrix", "math_csc_matrix", "math_csr_matrix")
target_end()

target("test_math_coo_matrix")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_coo_matrix.cpp")
    add_deps("math_coo_matrix", "math_dok_matrix", "math_lil_matrix", "math_csc_matrix", "math_csr_matrix")
target_end()

target("test_math_csc_matrix")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_csc_matrix.cpp")
    add_deps("math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csr_matrix")
target_end()

target("test_math_csr_matrix")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_csr_matrix.cpp")
    add_deps("math_csr_matrix", "math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csc_matrix")
target_end()

target("test_math_qdldl_dcmp")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_qdldl_dcmp.cpp")
    add_deps("math_qdldl_dcmp")
target_end()
