includes("curves/xmake.lua")
includes("functions/xmake.lua")
includes("mdfunctions/xmake.lua")
includes("dense/xmake.lua")
includes("sparse/xmake.lua")

target("test_math_fft")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../src")
    add_files("test_fft.cpp")
    add_deps("math_fft")
target_end()

target("test_math_chebyshev")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../src")
    add_files("test_chebyshev.cpp")
    add_deps("math_chebyshev", "math_utils")
target_end()

target("test_math_cubic_interpolation")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../src")
    add_files("test_cubic_interpolation.cpp")
    add_deps("math_cubic_interpolation")
target_end()

target("test_math_quintic_interpolation")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../src")
    add_files("test_quintic_interpolation.cpp")
    add_deps("math_quintic_interpolation")
target_end()

target("test_math_fixed")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../src")
    add_files("test_fixed.cpp")
    add_deps("math_fixed")
target_end()

target("test_math_polygon")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../src")
    add_files("test_polygon.cpp")
    add_deps("math_polygon")
target_end()
