target("test_bicycle_state")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_state.cpp")
    add_deps("bicycle_state")
target_end()

target("test_bicycle_kinematics_model")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_kinematics_model.cpp")
    add_deps("bicycle_kinematics_model", "math_vec2")
target_end()

target("test_bicycle_dynamics_model")
    add_rules("basjoo.cxx.test")
    add_includedirs("../../../../src")
    add_files("test_dynamics_model.cpp")
    add_deps("bicycle_dynamics_model")
target_end()
